builders:
  delegate_has_class_builder:
    import: "package:mhu_dart_builder/src/delegate/delegate.dart"
    builder_factories: ["delegateHasClassBuilder"]
    build_extensions: {".dart": [".g.has.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: [":delegate_compose_builder"]
  delegate_compose_builder:
    import: "package:mhu_dart_builder/src/delegate/delegate.dart"
    builder_factories: ["delegateComposeBuilder"]
    build_extensions: {".dart": [".g.compose.dart"]}
    auto_apply: none
    build_to: source
#    applies_builders: ["source_gen:combining_builder"]
