name: mhu_dart_builder
version: 1.0.5
description: Common tools used in the build process of my Dart and Flutter projects
repository: https://github.com/maprohu/mhu_dart_builder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_annotation:
    path: ../mhu_dart_annotation
  mhu_dart_sourcegen:
    path: ../mhu_dart_sourcegen

dependencies:
  mhu_dart_annotation: ^1.0.0
  mhu_dart_sourcegen: ^1.0.0

  analyzer: ^5.13.0
  collection: ^1.17.1
  fast_immutable_collections: ^9.1.5
  build: ^2.4.1
  recase: ^4.1.0
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
