name: mhu_dart_builder_example
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependency_overrides:
#  mhu_dart_commons:
#    path: ../../mhu_dart_commons
  mhu_dart_annotation:
    path: ../../mhu_dart_annotation
  mhu_dart_sourcegen:
    path: ../../mhu_dart_sourcegen

dependencies:
  mhu_dart_annotation: ^1.0.0
  path: ^1.8.3
#  mhu_dart_commons: ^1.0.9



dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
#  freezed: ^2.4.1
  mhu_dart_builder:
    path: ..

